# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "train": "01_data.ipynb",
         "images": "01_data.ipynb",
         "DanceData": "01_data.ipynb",
         "tsfm": "01_data.ipynb",
         "msk": "01_data.ipynb",
         "train_df": "01_data.ipynb",
         "valid_df": "01_data.ipynb",
         "train_ds": "01_data.ipynb",
         "valid_ds": "01_data.ipynb",
         "bs": "01_data.ipynb",
         "train_dl": "01_data.ipynb",
         "valid_dl": "01_data.ipynb",
         "show_batch": "01_data.ipynb"}

modules = ["core.py",
           "data.py"]

doc_url = "https://sonujha.github.io/hellonbdev/"

git_url = "https://github.com/sonujha/hellonbdev/tree/master/"

def custom_doc_links(name): return None
